name: LoginLocationFix
version: '${version}'
main: net.meano.loginlocationfix.LoginLocationFix
description: Fix player location when they login, prevent stuck in blocks
api-version: 1.19
authors: [ Meano, Dreeam ]
