name: Build LoginLocationFix

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Setup java
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

      - name: Release Artifacts
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "LoginLocationFix v0.12"
          automatic_release_tag: "0.12"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs"
          prerelease: false
