name: Build LoginLocationFix

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Release Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "LoginLocationFix v0.9"
          automatic_release_tag: "0.9"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs"
          prerelease: false
